# Generated by Django 3.1.3 on 2020-12-11 17:47

import ML.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_patientxray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientxray',
            name='Xray_image',
            field=models.ImageField(upload_to=ML.models.upload_to),
        ),
    ]
